steps:
- name: 'eu.gcr.io/tes-wes/taskmaster:$TAG_NAME'
  args: ['build', '-t', 'eu.gcr.io/tes-wes/taskmaster:$TAG_NAME', '-f', 'dockerfiles/taskmaster/Dockerfile']
images: ['eu.gcr.io/tes-wes/taskmaster:$TAG_NAME']
