apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: tesk
  name: tesk-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tesk
    spec:
      containers:
      - image: erikvdbergh/tesk
        name: tesk
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: 100m
