{{ if .Values.ingress.active }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules {{ if .Values.ingress.tls_letsencrypt }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.tls_letsencrypt.annotations.ingressclass }}
    kubernetes.io/tls-acme: "{{ .Values.ingress.tls_letsencrypt.annotations.tlsacme }}"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls_letsencrypt.annotations.clusterissuer }}
  {{ end }}
spec: {{ if .Values.ingress.tls_secret_name }}
  tls:
  - hosts:
    - {{ .Values.host_name }}
    secretName: {{ .Values.ingress.tls_secret_name }} {{ end }}
  rules:
  - host: {{ .Values.host_name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: tesk-api
          servicePort: {{ .Values.tesk.port }}
{{ end }}
